// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ08blxv75JnBgg1VqSj0ez5clZld_PZg',
    appId: '1:669854074093:web:0445bb3393e814f13478e4',
    messagingSenderId: '669854074093',
    projectId: 'cmsc23-project-44dd8',
    authDomain: 'cmsc23-project-44dd8.firebaseapp.com',
    storageBucket: 'cmsc23-project-44dd8.appspot.com',
    measurementId: 'G-TJKYVCQ66K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdTGKliUcyQAoWJJot1L12h57C3CPOZ6U',
    appId: '1:669854074093:android:9a8c8054c16534803478e4',
    messagingSenderId: '669854074093',
    projectId: 'cmsc23-project-44dd8',
    storageBucket: 'cmsc23-project-44dd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV_7aZ874-00cXrVVua5GnIWnWnBn3f98',
    appId: '1:669854074093:ios:2761144626d12c4a3478e4',
    messagingSenderId: '669854074093',
    projectId: 'cmsc23-project-44dd8',
    storageBucket: 'cmsc23-project-44dd8.appspot.com',
    iosBundleId: 'com.example.donationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV_7aZ874-00cXrVVua5GnIWnWnBn3f98',
    appId: '1:669854074093:ios:2761144626d12c4a3478e4',
    messagingSenderId: '669854074093',
    projectId: 'cmsc23-project-44dd8',
    storageBucket: 'cmsc23-project-44dd8.appspot.com',
    iosBundleId: 'com.example.donationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ08blxv75JnBgg1VqSj0ez5clZld_PZg',
    appId: '1:669854074093:web:786c51900403b6cf3478e4',
    messagingSenderId: '669854074093',
    projectId: 'cmsc23-project-44dd8',
    authDomain: 'cmsc23-project-44dd8.firebaseapp.com',
    storageBucket: 'cmsc23-project-44dd8.appspot.com',
    measurementId: 'G-C2QRK4E6E9',
  );
}
